package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

	private static final long serialVersionUID = 1L;

	private int len1;

	private int len2;

	private JoinPredicate p;

	private DbIterator child1;

	private DbIterator child2;

	private TupleDesc td;

	private DbIterator joinRes;

	/**
	 * Constructor. Accepts to children to join and the predicate to join them on
	 * 
	 * @param p      The predicate to use to join the children
	 * @param child1 Iterator for the left(outer) relation to join
	 * @param child2 Iterator for the right(inner) relation to join
	 */
	public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
		// some code goes here
		this.len1 = child1.getTupleDesc().numFields();
		this.len2 = child2.getTupleDesc().numFields();
		this.p = p;
		this.child1 = child1;
		this.child2 = child2;
		this.td = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());// 元组描述不去重
		joinRes = null;
	}

	public JoinPredicate getJoinPredicate() {
		// some code goes here
		return p;
	}

	/**
	 * @return the field name of join field1. Should be quantified by alias or table
	 *         name.
	 */
	public String getJoinField1Name() {
		// some code goes here
		return child1.getTupleDesc().getFieldName(p.getField1());
	}

	/**
	 * @return the field name of join field2. Should be quantified by alias or table
	 *         name.
	 */
	public String getJoinField2Name() {
		// some code goes here
		return child2.getTupleDesc().getFieldName(p.getField2());
	}

	/**
	 * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
	 *      implementation logic.
	 */
	public TupleDesc getTupleDesc() {
		// some code goes here
		return td;
	}

	public void open() throws DbException, NoSuchElementException, TransactionAbortedException {
		// some code goes here
		super.open();
		child1.open();
		child2.open();
		joinRes = nestedLoopJoin();
		joinRes.open();
	}

	/**
	 * 等待优化的算法
	 */
	private TupleIterator nestedLoopJoin() throws DbException, TransactionAbortedException {
		List<Tuple> list = new LinkedList<Tuple>();
		while (child1.hasNext()) {
			Tuple out = child1.next();
			while (child2.hasNext()) {
				Tuple in = child2.next();
				if (p.filter(out, in)) {
					Tuple newTuple = mergeTuples(out, in);
					list.add(newTuple);
				}
			}
			child2.rewind();// 低效
		}
		return new TupleIterator(td, list);
	}

	/* 联接两个元组,没有去重 */
	private Tuple mergeTuples(Tuple out, Tuple in) {
		Tuple newTuple = new Tuple(td);
		for (int i = 0; i < len1; i++) {
			Field f = out.getField(i);
			newTuple.setField(i, f);
		}
		for (int i = 0; i < len2; i++) {
			Field f = in.getField(i);
			newTuple.setField(len1 + i, f);
		}
		return newTuple;
	}

	public void close() {
		// some code goes here
		joinRes.close();
		child2.close();
		child1.close();
		super.close();
	}

	public void rewind() throws DbException, TransactionAbortedException {
		// some code goes here
		child1.rewind();
		child2.rewind();
		joinRes.rewind();
	}

	/**
	 * Returns the next tuple generated by the join, or null if there are no more
	 * tuples. Logically, this is the next tuple in r1 cross r2 that satisfies the
	 * join predicate. There are many possible implementations; the simplest is a
	 * nested loops join.
	 * <p>
	 * Note that the tuples returned from this particular implementation of Join are
	 * simply the concatenation of joining tuples from the left and right relation.
	 * Therefore, if an equality predicate is used there will be two copies of the
	 * join attribute in the results. (Removing such duplicate columns can be done
	 * with an additional projection operator if needed.)
	 * <p>
	 * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6}, joined
	 * on equality of the first column, then this returns {1,2,3,1,5,6}.
	 * 
	 * @return The next matching tuple.
	 * @see JoinPredicate#filter
	 */
	protected Tuple fetchNext() throws TransactionAbortedException, DbException {
		// some code goes here
		while (joinRes.hasNext()) {
			Tuple temp = joinRes.next();
			return temp;
		}
		return null;
	}

	@Override
	public DbIterator[] getChildren() {
		// some code goes here
		return new DbIterator[] { child1, child2 };
	}

	@Override
	public void setChildren(DbIterator[] children) {
		// some code goes here
		child1 = children[0];
		child2 = children[1];
	}

}
